# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F3D4D1
background         #1D1D1F
cursor             #9C96A8

active_tab_foreground     #1D1D1F
active_tab_background     #F3D4D1
inactive_tab_foreground   #F3D4D1
inactive_tab_background   #1D1D1F

active_border_color   #F3D4D1
inactive_border_color #1D1D1F
bell_border_color     #173949

color0      #434346
color1		#173949
color2		#34425F
color3		#792F5E
color4		#1A6379
color5		#1A6880
color6		#A5625D
color7		#E5B9B5
color8		#A0817F
color9		#1E4D61
color10		#46587F
color11		#A13F7E
color12		#2384A2
color13		#238BAA
color14		#DC837C
color15		#E5B9B5
