# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1D1D1F)
$foreground = rgb(F3D4D1)
$color0 = rgb(434346)
$color1 = rgb(173949)
$color2 = rgb(34425F)
$color3 = rgb(792F5E)
$color4 = rgb(1A6379)
$color5 = rgb(1A6880)
$color6 = rgb(A5625D)
$color7 = rgb(E5B9B5)
$color8 = rgb(A0817F)
$color9 = rgb(1E4D61)
$color10 = rgb(46587F)
$color11 = rgb(A13F7E)
$color12 = rgb(2384A2)
$color13 = rgb(238BAA)
$color14 = rgb(DC837C)
$color15 = rgb(E5B9B5)
